name: Make ROMs

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Try urllib
        run: python3 -c 'import urllib.request; print(urllib.request.urlopen("https://github.com").code)'
      - name: Clone UEF2ROM
        run: git clone https://github.com/stardot/UEF2ROM
      - name: Fetch resources
        run: python3 fetch-uefs.py
      - name: Create scripts
        run: python3 csv2scripts.py
      - name: Run the batch script
        run: PATH=UEF2ROM:$PATH python3 batch.py
      - uses: actions/upload-artifact@v3
        with:
          name: Converted ROMs
          path: ROMs
