name: Make ROMs

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Ophis
        run: git clone https://github.com/michaelcmartin/Ophis
      - name: Clone UEF2ROM
        run: git clone -b python3 https://github.com/stardot/UEF2ROM
      - name: Fetch resources
        run: python3 fetch-uefs.py
      - name: Create scripts
        run: python3 csv2scripts.py
      - name: Create another script
        run: python3 disks2uefs.py
      - name: Create UEFs
        run: PATH=UEF2ROM:$PATH sh disks.sh
      - name: Run the batch script
        run: PATH=Ophis/bin:UEF2ROM:$PATH sh batch.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Converted ROMs
          path: ROMs
      - name: Upload GitHub Pages artifacts
        uses: actions/upload-pages-artifact@v0
        with:
          path: ROMs

  deploy:

    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
